name: Scope Testing

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Scope for iOS
      uses: undefinedlabs/scope-for-ios-action@v1
      with:
        dsn: ${{ secrets.SCOPE_DSN }}
        project: Client.xcodeproj
        scheme: Fennec
        instrumentHttpPayloads: true


